### ISSUE TITLE
[Fispace Store and Applications]: issue with cross-origin framing when using Firefox browser

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#22] opened 2015-05-12 10:04 UTC
I am using the Firefox browser, version 37.0.2:
Fispace Store (WStore) and Applications (Wirecloud) are not accessible and only an empty white space is shown.

The console log shows errors with cross-origin framing:

```
Load denied by X-Frame-Options: http://auth.ee.fispace.eu:8080/auth/realms/fispace/tokens/login?state=37W55KPB0cI1czlhOF9OhxD6kVcLKBQt&redirect_uri=http%3A%2F%2F37.131.251.130%3A8088%2Fcomplete%2Ffiware%2F&response_type=code&client_id=wirecloud&next=%2F does not permit cross-origin framing.

Load denied by X-Frame-Options: http://auth.ee.fispace.eu:8080/auth/realms/fispace/tokens/login?state=sjwT9wSFN6naWNR6UWghZOTEgYQS0y37&redirect_uri=http%3A%2F%2F37.131.251.130%3A8000%2Fcomplete%2Ffiware%2F&response_type=code&client_id=wstore&next=/ does not permit cross-origin framing.
```

**Comment by rapw3k** [comment] 2015-05-27 08:11
Hi,
we had to forward this issue to FIspace team: https://bitbucket.org/fispace/phase3support/issue/31/fispace-and-applications-issue-with-cross

**Comment by rapw3k** [comment] 2015-05-29 08:31
@gitoni according to answer in bitbucket, X-Frame Options are part of Keycloak configuration

**Comment by gitoni** [comment] 2015-06-01 12:56
Does this mean it is a confirmed bug? Will they change the keycloak configuration soon?

**Comment by JanWillemKruize** [comment] 2015-06-02 09:36
Yes, confirmed configuration, quick fix requested, we will keep you posted.

**Comment by rapw3k** [comment] 2015-06-08 10:43
Hi @gitoni there has been some update, see https://bitbucket.org/fispace/phase3support/issue/31/fispace-and-applications-issue-with-cross.
They ask if you could test again and let us know the result.

**Comment by JanWillemKruize** [comment] 2015-06-15 09:13
please reopen issue if not fixed.

**Comment by gitoni** [comment] 2015-06-23 10:48
Hi,
I am reopening, because the issue is not fixed. Still the same empty white space when using the Firefox browser.

**Comment by JanWillemKruize** [comment] 2015-06-25 10:38
Please provide specific firefox version and check if same behaviour occurs on another browser as well (chrome for example). I will forward this information to the FIspace team so they can try to reproduce the issue.

**Comment by gitoni** [comment] 2015-06-25 18:08
It works fine with Chrome. 
I get this error with Firefox 38.0.5 on Windows 7. 
But I just found out that it works with Firefox 38.0.5 on Ubuntu 14.04.

So it might be something with my Firefox configuration or Windows Firewall whatever. Sorry for bothering you in that case. Will let you know if I can find out why it doesn't work for me.

**Comment by rapw3k** [comment] 2015-07-03 14:20
Thanks for the feedback, can we close this issue?

**Comment by gitoni** [comment] 2015-07-07 07:18
Hi,
well, it is not solved. But it is not blocking me and I can switch to Chrome when using FISPACE. 
If it is not reproducable by anbody else, you can probably close the issue.

**Comment by rapw3k** [comment] 2015-07-17 09:23
Hi @gitoni a question from FIspace team is if the problem occurs with a widget or just login to fispace?

**Comment by perezdf** [comment] 2015-07-17 09:38
Hi, if the problem is related with the connection by a widget, please, it could help, if you provide me/us the oauth client resource  you are using (just the name) and/or the widget for testing matters.

**Comment by gitoni** [comment] 2015-07-20 08:06
Hi perezdf,
the problem is probably related to keycloak client_id=wirecloud and client_id=wstore.

**Comment by perezdf** [comment] 2015-07-20 09:25
maybe it is my misunderstanding because in other cases, we are facing problems with the connectivity of widget. So this is not the case right? basically, using firefox 37.0.2 you go to frontend and after to store, and the cross-origin error comes out, right?

**Comment by gitoni** [comment] 2015-07-21 14:31
yes, right, it is not about the connectivity of a widget.
I login and everything works except the urls: 
http://37.131.251.117:8080/gui/fispace/main/store
and
http://37.131.251.117:8080/gui/fispace/main/wirecloud

**Comment by gitoni** [comment] 2015-07-22 06:05
But as I said earlier: it is probably because of some of my Firefox/Windows/Firewall configurations. It seems that it is not reproducible by others.

**Comment by perezdf** [comment] 2015-07-22 07:51
I think so also, sadly I dont have Windows

![snapshot](https://cloud.githubusercontent.com/assets/5735388/8820523/9884a1ce-3056-11e5-8269-5527c340ea64.jpg)

but with ubuntu/firefox 37.0.2 seems to work. I am sure you were suffering this issue, but looks quite specific and difficult to reproduce.

For the time being, I can nt help you more, sorry.
Paco

**Closed as completed** 2015-07-29 13:43 UTC
