### ISSUE TITLE
[Fispace Store]: resources not shown

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#21] opened 2015-05-12 09:42 UTC
I am able to register resources in the Fispace store by uploading a widget file. The message then says that the resource was sucessfully created.

But when I want to see the resources I just get a black screen and two empty info boxes with the title "User resources":
![store_view_resources](https://cloud.githubusercontent.com/assets/113715/7584178/da911c7a-f89b-11e4-8fe5-c9d0d306e16c.JPG)
![store_view_resources2](https://cloud.githubusercontent.com/assets/113715/7584181/ddfcb5d6-f89b-11e4-9657-042b71042477.JPG)

Browser: Google Chrome, version 42.0.2311.135

**Comment by rapw3k** [comment] 2015-05-27 08:09
Hi, 
we had to forward this query to FIspace team https://bitbucket.org/fispace/phase3support/issue/30/fispace-store

**Comment by gitoni** [comment] 2015-06-03 08:28
related issue: 
https://bitbucket.org/fispace/phase3support/issue/26/fispace-issue-from-sme

The javascript console logs the following errors when accessing the page http://37.131.251.117:8080/gui/fispace/main/store:

![store_js_console](https://cloud.githubusercontent.com/assets/113715/7955764/2493f90a-09db-11e5-9be2-72bc4ca4f5df.JPG)
(The last error messsage is only shown when "view resources" is selected)

**Comment by rapw3k** [comment] 2015-06-03 09:32
The issue has been marked as blocker, please keep track with Andres in bitbucket. If this is not solved today/tomorrow, I will also push other FIspace people.

**Comment by rapw3k** [comment] 2015-06-08 10:48
Hi @gitoni as you have probably see in https://bitbucket.org/fispace/phase3support/issue/30/fispace-store, FIspace team was able to reproduce this problem.
Since this is a GE error and not FISPACE they have requested support from the GEs development team.

**Comment by JanWillemKruize** [comment] 2015-06-15 09:12
Issue forwarded to WStore GE owner.

**Closed as completed by JanWillemKruize** 2015-06-15 09:12 UTC
